services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    ports:
      - "6767:6767"
    volumes:
      - ./config:/config
      - /opt/media/movies:/movies
      - /opt/media/shows:/tv
